"""Refuse a source distribution containing anything nobody allowed (§11).

Run against a built artifact:

    uv build --sdist -o dist
    uv run python scripts/check_sdist.py dist/*.tar.gz

Why this exists rather than another `.gitignore` line. The released
`rh_mcp-0.1.0.tar.gz` shipped `.claude/settings.local.json` — a developer's
local editor permissions, absent from every commit at the tagged revision,
carried in because hatchling's default sdist is "the working directory minus
what git ignores". An independent reviewer found it by rebuilding the sdist
from the pinned commit and diffing: the wheel matched byte for byte, the sdist
did not.

The distinction that matters is allowlist versus blocklist. Ignoring
`.claude/` would close that one case and leave the shape of it open, because
the failure was never about `.claude` specifically — it was that the artifact
is a function of somebody's working directory rather than of the commit. So
this script enumerates what a source distribution may contain and refuses
everything else, which means the next tool that writes a dotfile into a
maintainer's checkout fails CI instead of shipping.

Deliberately independent of `pyproject.toml`. Reading the packaging config to
check the package would make this a test of whether hatchling can obey its own
`include` list, which is not in doubt. The point is that two people had to
agree, in two places, before a new path can reach PyPI.

No credential was found in the file that shipped. This is a reproducibility
control, not an incident response: an sdist that is not derivable from the
commit cannot be verified against it, and rebuilding-and-comparing is the only
integrity check a consumer can run without trusting the publisher.
"""

from __future__ import annotations

import sys
import tarfile
from pathlib import Path, PurePosixPath

# Exact filenames permitted at the root of the distribution. `PKG-INFO` is
# generated by the build backend; everything else is committed.
ALLOWED_ROOT_FILES = frozenset(
    {
        # Added by hatchling itself, not by the `include` list, and committed.
        ".gitignore",
        "AGENTS.md",
        "CHANGELOG.md",
        "DESIGN.md",
        "INDEPENDENT_SECURITY_REVIEW.md",
        "LICENSE",
        "NOTICE",
        "PKG-INFO",
        "README.md",
        "pyproject.toml",
        "uv.lock",
    }
)

# Directory prefix -> the file suffixes permitted beneath it. Both halves are
# load-bearing: the prefix stops a whole directory appearing, and the suffix
# set stops a stray artifact appearing inside a directory that is allowed.
# `.json` under `src/rh_mcp` is the reviewed manifest and nothing else — see
# `REQUIRED_PATHS`.
ALLOWED_DIRECTORIES: dict[str, frozenset[str]] = {
    "src/rh_mcp/": frozenset({".py", ".json"}),
    "tests/": frozenset({".py"}),
    "scripts/": frozenset({".py"}),
    "security-review/": frozenset({".md", ".py"}),
    ".github/workflows/": frozenset({".yml"}),
}

# An allowlist alone cannot fail an *empty* archive, and a packaging change
# that silently dropped the manifest would leave every consumer with a gateway
# that can never become ready. These must be present.
REQUIRED_PATHS = frozenset(
    {
        "PKG-INFO",
        "pyproject.toml",
        "LICENSE",
        "NOTICE",
        "src/rh_mcp/__init__.py",
        "src/rh_mcp/gateway.py",
        "src/rh_mcp/manifests/read-manifest.json",
    }
)


def relative_members(archive: Path) -> tuple[list[str], list[str]]:
    """Split the sdist into regular files and everything else.

    Paths come back with the `<name>-<version>/` root removed so the allowlist
    can be written the way the repository is laid out.

    Anything that is not a regular file — a symlink, a hard link, a device
    node — is a finding in its own right and is never matched against the
    allowlist. An sdist has no legitimate use for one, and a symlink whose
    target escapes the extraction root is the oldest tarball attack there is;
    a `.py` suffix must not be able to launder it past a directory rule.
    """
    files: list[str] = []
    irregular: list[str] = []
    with tarfile.open(archive, "r:gz") as tar:
        for member in tar.getmembers():
            if member.isdir():
                continue
            path = PurePosixPath(member.name)
            relative = str(PurePosixPath(*path.parts[1:])) if len(path.parts) > 1 else member.name
            if member.isfile():
                files.append(relative)
            else:
                irregular.append(
                    f"{relative}: not a regular file (tar type {member.type!r}"
                    + (f", links to {member.linkname!r}" if member.linkname else "")
                    + ")"
                )
    return files, irregular


def unexpected(members: list[str]) -> list[str]:
    findings: list[str] = []
    for name in members:
        if "/" not in name:
            if name not in ALLOWED_ROOT_FILES:
                findings.append(f"{name}: not an allowed root file")
            continue
        for prefix, suffixes in ALLOWED_DIRECTORIES.items():
            if name.startswith(prefix):
                if PurePosixPath(name).suffix not in suffixes:
                    findings.append(
                        f"{name}: {PurePosixPath(name).suffix or 'no'} suffix "
                        f"not allowed under {prefix}"
                    )
                break
        else:
            findings.append(f"{name}: no allowed directory prefix")
    return findings


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: check_sdist.py <path-to-sdist.tar.gz>", file=sys.stderr)
        return 2
    archive = Path(argv[1])
    if not archive.is_file():
        print(f"no such sdist: {archive}", file=sys.stderr)
        return 2

    members, irregular = relative_members(archive)
    findings = irregular + unexpected(members)
    missing = sorted(REQUIRED_PATHS - set(members))

    for finding in findings:
        print(f"UNEXPECTED  {finding}", file=sys.stderr)
    for path in missing:
        print(f"MISSING     {path}", file=sys.stderr)

    if findings or missing:
        print(
            f"\n{archive.name}: {len(findings)} unexpected, {len(missing)} missing "
            f"of {len(members)} files. A source distribution must be a function "
            f"of the commit, not of a working directory.",
            file=sys.stderr,
        )
        return 1

    print(f"{archive.name}: {len(members)} files, all allowlisted")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
